from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="LBOS-Ai",
    version="0.1.0",
    author="Lihan Badenhorst",
    description="A state-of-the-art AI assistant with agent framework and multimodal capabilities",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/coolboy17289/v4",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "accelerate>=0.20.0",
        "bitsandbytes>=0.41.0",
        "faiss-cpu>=1.7.4",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "transformers[torch]>=4.30.0",
        "accelerate>=0.20.0",
        "bitsandbytes>=0.41.0",
        "fastapi>=0.95.0",
        "uvicorn[standard]>=0.22.0",
        "python-multipart>=0.0.6",
        "python-dotenv>=1.0.0",
        "pydantic>=2.0.0",
        "sqlalchemy>=2.0.0",
        "alembic>=1.12.0",
        "psycopg2-binary>=2.9.0",
        "redis>=4.5.0",
        "numpy>=1.24.0",
        "pillow>=9.0.0",
        "opencv-python>=4.7.0",
        "pytesseract>=0.3.10",
        "pdfplumber>=0.10.0",
        "python-docx>=0.8.11",
        "markdown>=3.4.0",
        "beautifulsoup4>=4.12.0",
        "requests>=2.31.0",
        "yt-dlp>=2023.7.6",
        "openai-whisper>=20231117",
        "gitpython>=3.1.0",
        "github>=3.1.0",
        "neo4j>=5.0.0",
        "networkx>=3.0",
        "sentence-transformers>=2.2.0",
        "transformers[torch]>=4.30.0",
        "accelerate>=0.20.0",
        "bitsandbytes>=0.41.0",
        "peft>=0.4.0",
        "trl>=0.4.0",
        "datasets>=2.10.0",
        "evaluate>=0.4.0",
        " accelerate>=0.20.0",
        "bitsandbytes>=0.41.0",
        "transformers>=4.30.0",
        "accelerate>=0.20.0",
        "bitsandbytes>=0.41.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
            "pre-commit>=3.0.0",
        ],
        "gpu": [
            "torch[cuda]>=2.0.0",
            "faiss-gpu>=1.7.4",
        ],
    },
)