"""
Learning Engine for continuous learning from user interactions
"""

import logging
import json
import time
from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
import hashlib

logger = logging.getLogger(__name__)


class LearningEngine:
    """Manages continuous learning from user interactions and feedback"""

    def __init__(self, storage_path: str = "./learning_data"):
        self.storage_path = storage_path
        self.feedback_buffer: List[Dict[str, Any]] = []
        self.learning_patterns: Dict[str, Any] = {}
        self.model_performance_history: List[Dict[str, Any]] = []

        # Ensure storage directory exists
        import os
        os.makedirs(self.storage_path, exist_ok=True)

        # Load existing learning data if available
        self._load_learning_data()

    def record_interaction(self, interaction_type: str,
                          input_data: Dict[str, Any],
                          output_data: Dict[str, Any],
                          user_feedback: Optional[Dict[str, Any]] = None,
                          context: Optional[Dict[str, Any]] = None) -> str:
        """
        Record a user interaction for learning

        Args:
            interaction_type: Type of interaction (e.g., 'chat', 'code_generation', 'research')
            input_data: Input provided to the system
            output_data: Output generated by the system
            user_feedback: Feedback from the user (optional)
            context: Additional context (optional)

        Returns:
            str: ID of the recorded interaction
        """
        interaction_id = self._generate_interaction_id(
            interaction_type, input_data, output_data
        )

        interaction_record = {
            "id": interaction_id,
            "timestamp": datetime.utcnow().isoformat(),
            "interaction_type": interaction_type,
            "input_data": input_data,
            "output_data": output_data,
            "user_feedback": user_feedback,
            "context": context or {},
            "processed": False
        }

        self.feedback_buffer.append(interaction_record)
        logger.debug(f"Recorded interaction {interaction_id} of type {interaction_type}")

        # If we have feedback, process it immediately for faster learning
        if user_feedback:
            self._process_feedback(interaction_id, user_feedback)

        # Periodically save to disk
        if len(self.feedback_buffer) >= 100:
            self._save_learning_data()

        return interaction_id

    def _process_feedback(self, interaction_id: str, feedback: Dict[str, Any]):
        """Process user feedback to extract learning signals"""
        try:
            # Find the interaction
            interaction = None
            for item in self.feedback_buffer:
                if item["id"] == interaction_id:
                    interaction = item
                    break

            if not interaction:
                # Look in stored data
                # In a real implementation, we'd search persistent storage
                pass

            if interaction:
                # Extract learning signals from feedback
                rating = feedback.get("rating", 0)  # Assume 1-5 scale
                corrections = feedback.get("corrections", {})
                tags = feedback.get("tags", [])

                # Update learning patterns
                self._update_learning_patterns(interaction, rating, corrections, tags)

                # Mark as processed
                interaction["processed"] = True

                # Log for analytics
                self._log_learning_event(interaction, feedback)

        except Exception as e:
            logger.error(f"Error processing feedback for interaction {interaction_id}: {e}")

    def _update_learning_patterns(self, interaction: Dict[str, Any],
                                rating: float, corrections: Dict[str, Any],
                                tags: List[str]):
        """Update internal learning patterns based on feedback"""
        interaction_type = interaction["interaction_type"]
        input_data = interaction["input_data"]
        output_data = interaction["output_data"]

        # Create a key for this type of interaction
        pattern_key = f"{interaction_type}:{hashlib.sha256(str(input_data).encode()).hexdigest()[:8]}"

        if pattern_key not in self.learning_patterns:
            self.learning_patterns[pattern_key] = {
                "count": 0,
                "positive_feedback": 0,
                "negative_feedback": 0,
                "corrections": {},
                "tags": {},
                "last_updated": datetime.utcnow().isoformat()
            }

        pattern = self.learning_patterns[pattern_key]
        pattern["count"] += 1

        if rating >= 4:  # Positive feedback
            pattern["positive_feedback"] += 1
        elif rating <= 2:  # Negative feedback
            pattern["negative_feedback"] += 1

        # Update corrections
        for key, value in corrections.items():
            if key not in pattern["corrections"]:
                pattern["corrections"][key] = {}
            if str(value) not in pattern["corrections"][key]:
                pattern["corrections"][key][str(value)] = 0
            pattern["corrections"][key][str(value)] += 1

        # Update tags
        for tag in tags:
            if tag not in pattern["tags"]:
                pattern["tags"][tag] = 0
            pattern["tags"][tag] += 1

        pattern["last_updated"] = datetime.utcnow().isoformat()

    def get_improvement_suggestions(self, interaction_type: str,
                                  input_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Get suggestions for improving performance on similar inputs

        Args:
            interaction_type: Type of interaction
            input_data: Input data to get suggestions for

        Returns:
            List of improvement suggestions
        """
        suggestions = []

        # Look for similar patterns in our learning data
        input_hash = hashlib.sha256(str(input_data).encode()).hexdigest()[:8]
        pattern_key = f"{interaction_type}:{input_hash}"

        if pattern_key in self.learning_patterns:
            pattern = self.learning_patterns[pattern_key]

            # If we have more negative than positive feedback, suggest improvement
            if pattern["negative_feedback"] > pattern["positive_feedback"]:
                confidence = min(0.9, pattern["negative_feedback"] / max(1, pattern["count"]))

                # Suggest based on common corrections
                for field, corrections in pattern["corrections"].items():
                    if corrections:
                        most_common_correction = max(corrections.items(), key=lambda x: x[1])
                        suggestions.append({
                            "type": "correction",
                            "field": field,
                            "suggested_value": most_common_correction[0],
                            "confidence": confidence,
                            "reasoning": f"Based on {most_common_correction[1]} corrections"
                        })

                # Suggest based on tags
                if pattern["tags"]:
                    most_common_tag = max(pattern["tags"].items(), key=lambda x: x[1])[0]
                    suggestions.append({
                        "type": "tag_suggestion",
                        "tag": most_common_tag,
                        "confidence": min(0.8, pattern["tags"][most_common_tag] / max(1, pattern["count"])),
                        "reasoning": f"Frequently associated with tag '{most_common_tag}'"
                    })

        return suggestions

    def record_model_performance(self, model_name: str, task_type: str,
                                metrics: Dict[str, float],
                                dataset_info: Optional[Dict[str, Any]] = None):
        """
        Record performance metrics for a model

        Args:
            model_name: Name of the model
            task_type: Type of task the model was evaluated on
            metrics: Dictionary of metric names to values
            dataset_info: Information about the dataset used for evaluation
        """
        record = {
            "timestamp": datetime.utcnow().isoformat(),
            "model_name": model_name,
            "task_type": task_type,
            "metrics": metrics,
            "dataset_info": dataset_info or {}
        }

        self.model_performance_history.append(record)
        logger.info(f"Recorded performance for {model_name} on {task_type}: {metrics}")

        # Check if performance has degraded significantly
        self._check_for_performance_regression(model_name, task_type, metrics)

    def _check_for_performance_regression(self, model_name: str, task_type: str,
                                        current_metrics: Dict[str, float]):
        """Check if model performance has regressed significantly"""
        # Get historical performance for this model/task
        historical = [
            record for record in self.model_performance_history
            if record["model_name"] == model_name and
               record["task_type"] == task_type
        ]

        if len(historical) < 2:
            return  # Not enough data to detect regression

        # Compare with the average of the last 5 performances
        recent = sorted(historical, key=lambda x: x["timestamp"])[-5:]
        if len(recent) < 2:
            return

        # For simplicity, check if the primary metric (assume first one) has dropped
        metric_names = list(current_metrics.keys())
        if not metric_names:
            return

        primary_metric = metric_names[0]
        current_value = current_metrics[primary_metric]

        historical_values = [r["metrics"].get(primary_metric, 0) for r in recent]
        avg_historical = sum(historical_values) / len(historical_values)

        # If performance dropped by more than 20%, flag for retraining
        if current_value < avg_historical * 0.8:
            self._trigger_retraining_alert(model_name, task_type, current_value, avg_historical)

    def _trigger_retraining_alert(self, model_name: str, task_type: str,
                                current_value: float, historical_value: float):
        """Trigger an alert that a model may need retraining"""
        alert = {
            "timestamp": datetime.utcnow().isoformat(),
            "model_name": model_name,
            "task_type": task_type,
            "current_performance": current_value,
            "historical_average": historical_value,
            "degradation_percent": (1 - current_value / historical_value) * 100,
            "suggested_action": "consider_retraining"
        }

        # In a real system, this would trigger a notification or automated retraining
        logger.warning(f"Performance degradation detected for {model_name}: {alert}")

        # Store the alert
        alert_file = f"{self.storage_path}/retraining_alerts.jsonl"
        with open(alert_file, 'a') as f:
            f.write(json.dumps(alert) + '\n')

    def get_learning_stats(self) -> Dict[str, Any]:
        """Get statistics about the learning process"""
        total_interactions = len(self.feedback_buffer)
        processed_interactions = len([i for i in self.feedback_buffer if i.get("processed", False)])

        feedback_count = len([i for i in self.feedback_buffer if i.get("user_feedback") is not None])

        return {
            "total_interactions_recorded": total_interactions,
            "processed_interactions": processed_interactions,
            "feedback_received": feedback_count,
            "unique_learning_patterns": len(self.learning_patterns),
            "model_performance_records": len(self.model_performance_history),
            "buffer_size": len(self.feedback_buffer)
        }

    def save_learning_data(self):
        """Save all learning data to persistent storage"""
        self._save_learning_data()
        self._save_learning_patterns()
        self._save_performance_history()

    def _save_learning_data(self):
        """Save the feedback buffer to disk"""
        if not self.feedback_buffer:
            return

        # Save to a daily file
        date_str = datetime.utcnow().strftime("%Y-%m-%d")
        filename = f"{self.storage_path}/interactions_{date_str}.jsonl"

        try:
            with open(filename, 'a') as f:
                for interaction in self.feedback_buffer:
                    # Mark as saved to avoid duplicates
                    if not interaction.get("saved_to_disk", False):
                        f.write(json.dumps(interaction) + '\n')
                        interaction["saved_to_disk"] = True
            logger.info(f"Saved {len(self.feedback_buffer)} interactions to {filename}")

            # Clear the buffer after saving
            self.feedback_buffer = [i for i in self.feedback_buffer if not i.get("saved_to_disk", False)]
        except Exception as e:
            logger.error(f"Failed to save learning data: {e}")

    def _save_learning_patterns(self):
        """Save learned patterns to disk"""
        try:
            filename = f"{self.storage_path}/learning_patterns.json"
            with open(filename, 'w') as f:
                json.dump(self.learning_patterns, f, indent=2)
            logger.info(f"Saved learning patterns to {filename}")
        except Exception as e:
            logger.error(f"Failed to save learning patterns: {e}")

    def _save_performance_history(self):
        """Save model performance history to disk"""
        try:
            filename = f"{self.storage_path}/model_performance.jsonl"
            with open(filename, 'a') as f:
                for record in self.model_performance_history:
                    f.write(json.dumps(record) + '\n')
            # Clear the in-memory history after saving to avoid duplication
            # In a real system, we might keep recent history in memory
            self.model_performance_history = []
            logger.info(f"Saved performance history to {filename}")
        except Exception as e:
            logger.error(f"Failed to save performance history: {e}")

    def _load_learning_data(self):
        """Load existing learning data from disk"""
        import os
        import glob

        try:
            # Load learning patterns
            patterns_file = f"{self.storage_path}/learning_patterns.json"
            if os.path.exists(patterns_file):
                with open(patterns_file, 'r') as f:
                    self.learning_patterns = json.load(f)
                logger.info(f"Loaded learning patterns from {patterns_file}")

            # Load performance history (limited to avoid memory issues)
            performance_file = f"{self.storage_path}/model_performance.jsonl"
            if os.path.exists(performance_file):
                # Only load the last 1000 entries to avoid memory issues
                with open(performance_file, 'r') as f:
                    lines = f.readlines()
                    for line in lines[-1000:]:  # Last 1000 lines
                        try:
                            self.model_performance_history.append(json.loads(line))
                        except json.JSONDecodeError:
                            continue
                logger.info(f"Loaded performance history from {performance_file}")

        except Exception as e:
            logger.error(f"Error loading learning data: {e}")

    def _generate_interaction_id(self, interaction_type: str,
                               input_data: Dict[str, Any],
                               output_data: Dict[str, Any]) -> str:
        """Generate a unique ID for an interaction"""
        # Create a hash of the interaction components
        data_string = f"{interaction_type}:{json.dumps(input_data, sort_keys=True)}:{json.dumps(output_data, sort_keys=True)}:{time.time()}"
        return hashlib.sha256(data_string.encode()).hexdigest()[:16]

    def _log_learning_event(self, interaction: Dict[str, Any], feedback: Dict[str, Any]):
        """Log a learning event for analytics"""
        # In a real system, this might go to a separate analytics system
        logger.info(f"Learning event: {interaction['interaction_type']} "
                    f"received feedback rating {feedback.get('rating', 'N/A')}")

    def shutdown(self):
        """Clean shutdown of the learning engine"""
        # Save any remaining data
        self.save_learning_data()
        logger.info("Learning engine shut down")


# Global learning engine instance
learning_engine = LearningEngine()